version: "3.3"
services:
  indexer:
    image: ghcr.io/calico-crusade/indexer/indexer:latest
    restart: always
    environment:
      - Match:Url=${MATCH_URL}
      - Redis:Connection=${REDIS_CONNECTION}
