version: "3.3"
services:
  indexer:
    image: ghcr.io/calico-crusade/indexer/indexer:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - cba-postg-vol:/var/lib/postgresql/data
    ports:
      - 8893:5432
